Nama = input("Nama                 : ")
NIM = input("NIM                  : ")
KelasParalel = input("Kelas Paralel        : ")
TTL = input("Tempat Tanggal Lahir : ")
Alamat = input("Alamat               : ")
Hobi = input("Hobby                : ")
NoHP = input("No. HP               : ")

print("Nama                 :", Nama)
print("NIM                  :", NIM)
print("Kelas Paralel        :", KelasParalel)
print("Tempat Tanggal Lahir :", TTL)
print("Alamat               :", Alamat)
print("Hobby                :", Hobi)
print("No. HP               :", NoHP)
